version: "3.3"
services:
  sdmrdfizer_DE4LC:
    image: sdmtib/sdmrdfizer:4.3.6
    hostname: sdmrdfizer_DE4LC 
    container_name: sdmrdfizer_DE4LC
    domainname: DE4LC
    volumes:
      - ./data:/data
      - ./rdf:/data/rdf-dump
      - ./KGC-DIS/SDM-RDFizer-Configs:/data/configs
      - ./KGC-DIS/CSV2RDF-RMLMappingRules:/data/mappings
      - ./scripts:/data/scripts
      - ./KGC-DIS:/data/ttl
    networks:
      - DE4LC
    depends_on:
      - DE4LCkg
    environment:
      - SPARQL_ENDPOINT_IP=DE4LCkg
      - SPARQL_ENDPOINT_USER=dba
      - SPARQL_ENDPOINT_PASSWD=dba
      - SPARQL_ENDPOINT_PORT=1111
      - SPARQL_ENDPOINT_GRAPH=http://research.tib.eu/DE4LC
      - RDF_DUMP_FOLDER_PATH=/data/rdf-dump/
      - TTL_DUMP_FOLDER_PATH=/data/ttl/
      - SPARQL_MAPPINGS_ENDPOINT_IP=DE4LC_mappings
      

  DE4LCkg:
    image: kemele/virtuoso:6-stable
    hostname: DE4LCkg
    container_name: DE4LCkg
    domainname: DE4LC
    volumes:
      - ./rdf-dump:/data
      - ./rdf:/data/rdf-dump
      - ./KGC-DIS:/data/ttl
    ports:
      - "8481:8890"
    networks:
      - DE4LC
      
  DE4LC_mappings:
    image: kemele/virtuoso:6-stable
    hostname: DE4LC_mappings
    container_name: DE4LC_mappings
    domainname: DE4LC
    volumes:
      - ./rdf-dump-mappings:/data
      - ./KGC-DIS:/data/ttl
    ports:
      - "8482:8890"
    networks:
      - DE4LC
 
#    DE4LC_exp_api:
#     image: sdmtib/DE4LC_exploration:2.0
#     hostname: DE4LC_exploration_api
#     container_name: DE4LC_exploration_api
#     domainname: DE4LC
#     ports:
#       - "18873:5000"
#     environment:
#       - ENDPOINT=http://node2.research.tib.eu:8893/sparql
#     networks:
#       - DE4LC
      
  DE4LC_dereferencing:
    image: asanchez75/pubby:v0.3.3
    hostname: pubby
    container_name: DE4LC_pubby
    domainname: DE4LC
    ports:
        - "8480:8080"
    networks:
      - DE4LC
    environment:
      SPARQL_ENDPOINT: "https://labs.tib.eu/sdm/DE4LC_kg/sparql"
      PROJECT_HOMEPAGE_URL: "http://research.tib.eu/DE4LC/"
      PROJECT_NAME: "DE4LC"
      DEFAULT_RESOURCE: "http://research.tib.eu/DE4LC/entity/C0168273"
      DEFAULT_NAMED_GRAPH: "http://research.tib.eu/DE4LC"
      COMMON_URI_PREFIX: "http://research.tib.eu/DE4LC/"
      WEB_RESOURCE_PREFIX: ""
      PUBBY_ROOT_URL: "https://research.tib.eu/DE4LC/"
    restart: always
    tty: true
    
          
  DE4LC_detrusty:
    image: sdmtib/detrusty:0.7.2
    hostname: detrusty
    container_name: DE4LC_detrusty
    domainname: DE4LC
    volumes:
      - ./DeTrusty/Config/:/DeTrusty/Config/
    ports:
      - "8483:5000"
    networks:
      - DE4LC
    depends_on:
      - DE4LCkg

networks:
  p4lucat:
    external: false
